@startuml
skinparam style strictuml
participant ":JeuDeDes" as jeu
participant "joueurs:\nMap<String, Joueur>" as joueurs

-> jeu : redemarrerJeu()
note right of jeu
selon Contrôleur
(JeuDeDés est
l'objet racine)
end note


jeu -> joueurs : clear()
note right of joueurs
selon Expert
end note




@enduml